// Generated by ../tools/generate_tables.py; Fs=50MHz/1040.
module pluck_note_table(input wire [6:0] note,
    output reg [9:0] length, output reg [15:0] fraction,
    output reg [24:0] reciprocal);
always @* begin
    case(note)
        7'd36: begin length=10'd736; fraction=16'd36000; reciprocal=25'd22795; end
        7'd37: begin length=10'd695; fraction=16'd19278; reciprocal=25'd24140; end
        7'd38: begin length=10'd656; fraction=16'd23232; reciprocal=25'd25575; end
        7'd39: begin length=10'd619; fraction=16'd39343; reciprocal=25'd27104; end
        7'd40: begin length=10'd584; fraction=16'd59574; reciprocal=25'd28728; end
        7'd41: begin length=10'd552; fraction=16'd10800; reciprocal=25'd30394; end
        7'd42: begin length=10'd521; fraction=16'd16932; reciprocal=25'd32202; end
        7'd43: begin length=10'd492; fraction=16'd5673; reciprocal=25'd34100; end
        7'd44: begin length=10'd464; fraction=16'd36179; reciprocal=25'd36158; end
        7'd45: begin length=10'd438; fraction=16'd36893; reciprocal=25'd38304; end
        7'd46: begin length=10'd414; fraction=16'd2129; reciprocal=25'd40525; end
        7'd47: begin length=10'd390; fraction=16'd57594; reciprocal=25'd43019; end
        7'd48: begin length=10'd369; fraction=16'd1616; reciprocal=25'd45467; end
        7'd49: begin length=10'd348; fraction=16'd26023; reciprocal=25'd48210; end
        7'd50: begin length=10'd328; fraction=16'd60768; reciprocal=25'd51150; end
        7'd51: begin length=10'd310; fraction=16'd36056; reciprocal=25'd54120; end
        7'd52: begin length=10'd293; fraction=16'd13403; reciprocal=25'd57260; end
        7'd53: begin length=10'd276; fraction=16'd54552; reciprocal=25'd60787; end
        7'd54: begin length=10'd261; fraction=16'd24850; reciprocal=25'd64281; end
        7'd55: begin length=10'd246; fraction=16'd51988; reciprocal=25'd68200; end
        7'd56: begin length=10'd233; fraction=16'd1706; reciprocal=25'd72005; end
        7'd57: begin length=10'd220; fraction=16'd2062; reciprocal=25'd76260; end
        7'd58: begin length=10'd207; fraction=16'd50216; reciprocal=25'd81049; end
        7'd59: begin length=10'd196; fraction=16'd12413; reciprocal=25'd85598; end
        7'd60: begin length=10'd185; fraction=16'd17192; reciprocal=25'd90688; end
        7'd61: begin length=10'd174; fraction=16'd62164; reciprocal=25'd96421; end
        7'd62: begin length=10'd165; fraction=16'd14000; reciprocal=25'd101680; end
        7'd63: begin length=10'd156; fraction=16'd1644; reciprocal=25'd107546; end
        7'd64: begin length=10'd147; fraction=16'd23086; reciprocal=25'd114131; end
        7'd65: begin length=10'd139; fraction=16'd10892; reciprocal=25'd120699; end
        7'd66: begin length=10'd131; fraction=16'd28809; reciprocal=25'd128070; end
        7'd67: begin length=10'd124; fraction=16'd9610; reciprocal=25'd135300; end
        7'd68: begin length=10'd117; fraction=16'd17237; reciprocal=25'd143395; end
        7'd69: begin length=10'd110; fraction=16'd50183; reciprocal=25'd152520; end
        7'd70: begin length=10'd104; fraction=16'd41492; reciprocal=25'd161319; end
        7'd71: begin length=10'd98; fraction=16'd55358; reciprocal=25'd171196; end
        7'd72: begin length=10'd93; fraction=16'd24980; reciprocal=25'd180400; end
        7'd73: begin length=10'd88; fraction=16'd14698; reciprocal=25'd190650; end
        7'd74: begin length=10'd83; fraction=16'd23384; reciprocal=25'd202135; end
        7'd75: begin length=10'd78; fraction=16'd49974; reciprocal=25'd215093; end
        7'd76: begin length=10'd74; fraction=16'd27927; reciprocal=25'd226719; end
        7'd77: begin length=10'd70; fraction=16'd21830; reciprocal=25'd239675; end
        7'd78: begin length=10'd66; fraction=16'd30788; reciprocal=25'd254200; end
        7'd79: begin length=10'd62; fraction=16'd53957; reciprocal=25'd270600; end
        7'd80: begin length=10'd59; fraction=16'd25002; reciprocal=25'd284360; end
        7'd81: begin length=10'd56; fraction=16'd8708; reciprocal=25'd299593; end
        7'd82: begin length=10'd53; fraction=16'd4362; reciprocal=25'd316551; end
        7'd83: begin length=10'd50; fraction=16'd11295; reciprocal=25'd335544; end
        7'd84: begin length=10'd47; fraction=16'd28874; reciprocal=25'd356962; end
        default: begin length=10'd185; fraction=16'd0; reciprocal=25'd90688; end
    endcase
end
endmodule
