"""Reproducible math tables; no recorded audio. Run with any Python 3."""
from pathlib import Path
import math

src = Path(__file__).resolve().parents[1] / 'src'
fs = 50_000_000 / 1040
notes = ['// Generated by tools/generate_tables.py; Fs=50 MHz/1040.',
         'module note_table(input wire [6:0] note, output reg [31:0] phase_step);',
         'always @* begin', '    case (note)']
for note in range(128):
    freq = 440 * 2 ** ((note - 69) / 12)
    step = round(freq * 2**32 / fs)
    notes.append(f"        7'd{note}: phase_step = 32'h{step:08X}; // {freq:.6f} Hz")
notes += ["        default: phase_step = 0;", '    endcase', 'end', 'endmodule', '']
(src / 'note_table.v').write_text('\n'.join(notes), encoding='ascii')

rom = ['// Generated mathematical single-cycle sine; 1024 points, signed 16 bits.',
       'module sine_rom(input wire clk, input wire [9:0] addr,',
       '    output reg signed [15:0] data = 0);',
       'always @(posedge clk) begin', '    case (addr)']
for i in range(1024):
    value = round(32767 * math.sin(2 * math.pi * i / 1024))
    rom.append(f"        10'd{i}: data <= 16'h{value & 0xffff:04X};")
rom += ["        default: data <= 0;", '    endcase', 'end', 'endmodule', '']
(src / 'sine_rom.v').write_text('\n'.join(rom), encoding='ascii')
print('Generated note_table.v and sine_rom.v')
