# Generated by source_manifest.py; edit source_manifest.json.
namespace eval audio_import {
    variable profiles
    variable profile_top
    variable default_bank {project/audio_core_v2/src/audio_v2_bank_stream.v}
    set profile_top(core) {audio_v2_core}
    set profiles(core) {
        project/final_dual_timbre/src/playable_button.v
        project/final_dual_timbre/src/stream_fifo.v
        project/final_dual_timbre/src/knob_gain.v
        project/final_dual_timbre/src/adsr_envelope.v
        project/final_dual_timbre/src/sine_rom.v
        project/final_dual_timbre/src/note_table.v
        project/final_dual_timbre/src/pluck_note_table.v
        project/custom_harmonic_lab/src/custom_harmonic_params.v
        project/five_timbre_core/src/gallery_keys.v
        project/audio_palette_lab/src/palette_sine.v
        project/audio_core_v1/src/audio_panel.v
        project/audio_parameter_lab/src/audio_parameter_service.v
        project/audio_fx_lab/src/short_room_reverb.v
        project/audio_fx_lab/src/vibrato_factor.v
        project/audio_core_v2/src/audio_v2_state.v
        project/audio_core_v2/src/audio_v2_pluck.v
        project/audio_core_v2/src/audio_v2_pool_slot.v
        project/audio_core_v2/src/audio_v2_tone.v
        project/audio_core_v2/src/audio_v2_bank_stream.v
        project/audio_core_v2/src/audio_v2_core.v
    }
    set profile_top(transport) {audio_snapshot_bridge}
    set profiles(transport) {
        project/audio_integration/rtl/audio_transport_reset.v
        project/audio_integration/rtl/audio_snapshot_bridge.v
        project/audio_integration/rtl/audio_pcm_bridge.v
        project/audio_integration/rtl/audio_command_bridge.v
    }
    set profile_top(integration) {audio_integration_example}
    set profiles(integration) {
        project/final_dual_timbre/src/playable_button.v
        project/final_dual_timbre/src/stream_fifo.v
        project/final_dual_timbre/src/knob_gain.v
        project/final_dual_timbre/src/adsr_envelope.v
        project/final_dual_timbre/src/sine_rom.v
        project/final_dual_timbre/src/note_table.v
        project/final_dual_timbre/src/pluck_note_table.v
        project/custom_harmonic_lab/src/custom_harmonic_params.v
        project/five_timbre_core/src/gallery_keys.v
        project/audio_palette_lab/src/palette_sine.v
        project/audio_core_v1/src/audio_panel.v
        project/audio_parameter_lab/src/audio_parameter_service.v
        project/audio_fx_lab/src/short_room_reverb.v
        project/audio_fx_lab/src/vibrato_factor.v
        project/audio_core_v2/src/audio_v2_state.v
        project/audio_core_v2/src/audio_v2_pluck.v
        project/audio_core_v2/src/audio_v2_pool_slot.v
        project/audio_core_v2/src/audio_v2_tone.v
        project/audio_core_v2/src/audio_v2_bank_stream.v
        project/audio_core_v2/src/audio_v2_core.v
        project/audio_integration/rtl/audio_transport_reset.v
        project/audio_integration/rtl/audio_snapshot_bridge.v
        project/audio_integration/rtl/audio_pcm_bridge.v
        project/audio_integration/rtl/audio_command_bridge.v
        project/audio_integration/examples/audio_integration_example.v
    }
    set profile_top(consumer) {audio_state_view}
    set profiles(consumer) {
        project/audio_integration/rtl/audio_transport_reset.v
        project/audio_integration/rtl/audio_snapshot_bridge.v
        project/audio_integration/rtl/audio_pcm_bridge.v
        project/audio_integration/rtl/audio_command_bridge.v
        project/audio_integration/examples/audio_state_view.v
        project/audio_integration/examples/audio_observer_mock.v
    }
}
