"""One portable HDL source list; no board constraints or copied audio RTL."""
from pathlib import Path
import argparse
import hashlib
import json
import xml.etree.ElementTree as ET

PACKAGE = Path(__file__).resolve().parents[1]
ROOT = PACKAGE.parents[1]
MANIFEST_PATH = Path(__file__).with_suffix(".json")


def manifest():
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def relative_path(value):
    path = (ROOT / value).resolve()
    relative = path.relative_to(ROOT).as_posix()
    if not path.is_file():
        raise ValueError(f"Missing package dependency: {relative}")
    if path.suffix != ".v":
        raise ValueError(f"Only explicit Verilog sources may be imported: {relative}")
    return relative


def sources(profile="core", bank_override=None):
    data = manifest()
    ordered = []
    visiting = set()

    def visit(name):
        if name in visiting:
            raise ValueError(f"Cyclic source profile: {name}")
        visiting.add(name)
        record = data["profiles"][name]
        for inherited in record["inherits"]:
            visit(inherited)
        for relative in record["sources"]:
            relative = relative_path(relative)
            if relative not in ordered:
                ordered.append(relative)
        visiting.remove(name)

    visit(profile)
    if bank_override is not None:
        default = data["default_bank"]
        if ordered.count(default) != 1:
            raise ValueError("A bank override requires exactly one core-bank entry")
        replacement = relative_path(bank_override)
        if replacement in ordered and replacement != default:
            raise ValueError("Bank override is already in the selected source profile")
        ordered[ordered.index(default)] = replacement
    return ordered


def tcl_manifest():
    data = manifest()
    lines = ["# Generated by source_manifest.py; edit source_manifest.json.",
             "namespace eval audio_import {", "    variable profiles",
             "    variable profile_top",
             f'    variable default_bank {{{data["default_bank"]}}}']
    for name, profile in data["profiles"].items():
        lines += [f'    set profile_top({name}) {{{profile["top"]}}}',
                  f'    set profiles({name}) {{']
        lines += [f"        {path}" for path in sources(name)]
        lines += ["    }"]
    return "\n".join(lines + ["}", ""])


def project_xml(destination, profile, top=None, bank_override=None):
    """Generate a source-only Designer project at a chosen workspace path."""
    data = manifest()
    destination = Path(destination).resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    project = ET.Element("Project")
    ET.SubElement(project, "Template").text = "FPGA"
    ET.SubElement(project, "Version").text = "5"
    device = data["device"]
    ET.SubElement(project, "Device", {"name": device["family"], "pn": device["part"]}).text = device["id"]
    listing = ET.SubElement(project, "FileList")
    import os
    for relative in sources(profile, bank_override):
        path = Path(os.path.relpath(ROOT / relative, destination.parent)).as_posix()
        ET.SubElement(listing, "File", {"path": path, "type": "file.verilog", "enable": "1"})
    ET.indent(project)
    ET.ElementTree(project).write(destination, encoding="UTF-8", xml_declaration=True)
    return top or data["profiles"][profile]["top"]


def fingerprints(profile="core", bank_override=None):
    return {path: hashlib.sha256((ROOT / path).read_bytes()).hexdigest()
            for path in sources(profile, bank_override)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", choices=manifest()["profiles"], default="core")
    parser.add_argument("--bank", help="Explicit repository-relative qualified bank replacement")
    parser.add_argument("--format", choices=("files", "json", "tcl"), default="files")
    parser.add_argument("--write-tcl", action="store_true", help="Refresh the generated Tcl manifest")
    parser.add_argument("--gprj", help="Generate a source-only .gprj (never performs PnR)")
    parser.add_argument("--top", help="Top to report for a generated source-only project")
    args = parser.parse_args()
    if args.write_tcl:
        Path(__file__).with_suffix(".tcl").write_text(tcl_manifest(), encoding="ascii")
    if args.gprj:
        top = project_xml(args.gprj, args.profile, args.top, args.bank)
        print(f"SOURCE_PROJECT_WRITTEN top={top}; no CST/SDC or board-I/O claims")
    elif args.format == "tcl":
        print(tcl_manifest(), end="")
    elif args.format == "json":
        print(json.dumps({"profile": args.profile, "top": manifest()["profiles"][args.profile]["top"],
                          "sources": sources(args.profile, args.bank),
                          "source_sha256": fingerprints(args.profile, args.bank)}, indent=2))
    else:
        print("\n".join(sources(args.profile, args.bank)))


if __name__ == "__main__":
    main()
