"""Generate mathematical ROM and one explicit Designer project per candidate."""
from pathlib import Path
import math
HERE=Path(__file__).resolve().parents[1]
VARIANTS=['00_shared_reference','01_piano_precision','02_piano_soft',
          '03_piano_bright','04_clean_reed','05_pluck_detail','06_pluck_warm']
SUPPORT=['playable_button','playable_led','matrix_scanner','ec11_input','stream_fifo',
         'knob_gain','knob_volume_table','adsr_envelope','sine_rom','note_table',
         'pluck_note_table','pt8211_tx']

def main():
    lines=['// Mathematical periodic sine, 4096 x 16. Generated by tools/generate.py.',
           'module palette_sine(input wire clk,input wire [11:0] addr,output reg signed [15:0] data=0);',
           'always @(posedge clk) case(addr)']
    lines += [f"12'd{i}:data<=16'h{round(math.sin(2*math.pi*i/4096)*32767)&65535:04x};" for i in range(4096)]
    (HERE/'src/palette_sine.v').write_text('\n'.join(lines+['endcase','endmodule'])+'\n',encoding='utf-8')
    sources=sorted(f'../../src/{p.name}' for p in (HERE/'src').glob('*.v'))
    sources += [f'../../../final_dual_timbre/src/{s}.v' for s in SUPPORT]
    for profile,name in enumerate(VARIANTS):
        v=HERE/'variants'/name; v.mkdir(parents=True,exist_ok=True)
        top='palette_'+name
        (v/'top.v').write_text(f'''// Generated wrapper: only this profile changes between projects.
module {top}(input wire sys_clk,enc_a,enc_b,input wire [2:0] button_n,
    input wire [3:0] matrix_col_n,output wire [3:0] matrix_row_n,
    output wire hp_bck,hp_ws,hp_din,pa_en,status_led);
    palette_top #(.PROFILE({profile})) dut(sys_clk,enc_a,enc_b,button_n,matrix_col_n,
        matrix_row_n,hp_bck,hp_ws,hp_din,pa_en,status_led);
endmodule
''',encoding='utf-8')
        files=[(s,'verilog') for s in ['top.v']+sources]+[('../../src/palette.cst','cst'),('../../src/palette.sdc','sdc')]
        xml='\n'.join(f'    <File path="{s}" type="file.{t}" enable="1" />' for s,t in files)
        (v/(name+'.gprj')).write_text(f'''<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gowin-fpga-project>
<Project><Template>FPGA</Template><Version>5</Version>
  <Device name="GW5AT-60B" pn="GW5AT-LV60PG484AC1/I0">gw5at60b-002</Device>
  <FileList>
{xml}
  </FileList>
</Project>
''',encoding='utf-8')
        (v/'build.tcl').write_text(f'''set project_dir [file dirname [file normalize [info script]]]
open_project [file join $project_dir {name}.gprj]
set_option -top_module {top}
set_option -output_base_name {name}
run all
''',encoding='utf-8')
    print('Generated seven explicit projects and sine ROM.')
if __name__=='__main__': main()
